version: "3.5"
name: lakefs-mount-demo
services:
  jupyter-notebook:
    build: ./jupyter
    privileged: true
    environment:
      # log-level is set to WARN because of noisy stdout problem
      # -> See https://github.com/jupyter-server/jupyter_server/issues/1279
      - NOTEBOOK_ARGS=--log-level='WARN' --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/root --allow-root
      - NB_USER=root
      - NB_UID=0
      - NB_GID=0
      - CHOWN_HOME=yes
    working_dir: /root
    ports:
      - 8892:8888 # Jupyter
    volumes:
      - $PWD:/root
      - $PWD/../../data/alpaca_training_imgs:/root/alpaca_training_imgs

  lakefs:
    image: treeverse/lakefs:1
    pull_policy: always
    ports:
      - "8084:8000"
    depends_on:
      postgres:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    environment:
      - LAKEFS_BLOCKSTORE_TYPE=s3
      - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE=true
      - LAKEFS_BLOCKSTORE_S3_ENDPOINT=http://minio:9000
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=minioadmin
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY=minioadmin
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=some random secret string
      - LAKEFS_LOGGING_LEVEL=INFO
      - LAKEFS_STATS_ENABLED=${LAKEFS_STATS_ENABLED:-1}
      - LAKECTL_CREDENTIALS_ACCESS_KEY_ID=AKIAIOSFOLKFSSAMPLES
      - LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - LAKECTL_SERVER_ENDPOINT_URL=http://localhost:8000
      - LAKEFS_DATABASE_TYPE=postgres
      - LAKEFS_DATABASE_POSTGRES_CONNECTION_STRING=postgres://lakefs:lakefs@postgres/postgres?sslmode=disable
      - LAKEFS_AUTH_API_ENDPOINT=http://fluffy:9006/api/v1
      - LAKEFS_AUTH_UI_CONFIG_RBAC=internal
    entrypoint: ["/bin/sh", "-c"]
    command:
        - |
          lakefs setup --user-name everything-bagel --access-key-id "$$LAKECTL_CREDENTIALS_ACCESS_KEY_ID" --secret-access-key "$$LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY" || true
          lakefs run &
          echo "---- Creating repository ----"
          wait-for -t 60 lakefs:8000 -- curl -u "$$LAKECTL_CREDENTIALS_ACCESS_KEY_ID":"$$LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY" -X POST -H "Content-Type: application/json" -d '{ "name": "quickstart", "storage_namespace": "s3://quickstart", "default_branch": "main", "sample_data": true }' http://localhost:8000/api/v1/repositories || true
          echo ""
          wait-for -t 60 minio:9000 && echo '------------------------------------------------

                MinIO admin:   http://127.0.0.1:9005/
                
                               Username : minioadmin
                               Password : minioadmin
                '
          echo "------------------------------------------------"
          wait-for -t 60 jupyter-notebook:8888 && echo '

                Jupyter:       http://127.0.0.1:8894/
                '
          echo "------------------------------------------------"
          echo ""
          echo "lakeFS Web UI: http://127.0.0.1:8084/      >(.ï¼¿.)<"
          echo "                                             (  )_ "
          echo ""
          echo "                Access Key ID    : $$LAKECTL_CREDENTIALS_ACCESS_KEY_ID"
          echo "                Secret Access Key: $$LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY"
          echo ""
          echo "-------- Let's go and have axolotl fun! --------"
          echo ""
          wait
    profiles:
      - local-lakefs-enterprise

  minio-setup:
    image: minio/mc:RELEASE.2023-05-18T16-59-00Z
    environment:
        - MC_HOST_lakefs=http://minioadmin:minioadmin@minio:9000
    depends_on:
      - minio
    volumes:
      - ../../data:/data
    entrypoint: ["/bin/sh", "-c"]
    command:
        - |
          mc mb lakefs/quickstart lakefs/example lakefs/sample-data
          mc cp --recursive /data/* lakefs/sample-data 1>/dev/null # don't be so noisy ðŸ¤«
    profiles:
      - local-lakefs-enterprise

  minio:
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    ports:
      - "9004:9000"
      - "9005:9001"
    entrypoint: ["minio", "server", "/data", "--console-address", ":9001"]
    profiles:
      - local-lakefs-enterprise

  postgres:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: lakefs
      POSTGRES_PASSWORD: lakefs
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "lakefs"]
      interval: 10s
      retries: 5
      start_period: 5s
    profiles:
      - local-lakefs-enterprise

  fluffy:
    image: "${FLUFFY_REPO:-treeverse}/fluffy:${TAG:-latest}"
    command: "${COMMAND:-run}"
    ports:
      - "8085:8000"
      - "9006:9000"
    depends_on:
      - "postgres"
    environment:
      - FLUFFY_LOGGING_LEVEL=INFO
      - FLUFFY_DATABASE_TYPE=postgres
      - FLUFFY_DATABASE_POSTGRES_CONNECTION_STRING=postgres://lakefs:lakefs@postgres/postgres?sslmode=disable
      - FLUFFY_AUTH_ENCRYPT_SECRET_KEY=some random secret string
      - FLUFFY_AUTH_SERVE_LISTEN_ADDRESS=0.0.0.0:9006
    entrypoint: [ "/app/wait-for", "postgres:5432", "--", "/app/fluffy" ]
    profiles:
      - local-lakefs-enterprise

networks:
  default:
    name: bagel
